### ISSUE TITLE
beatpicker.js for mobile

### ISSUE THREAD

**Issue by cawo88** [ACT1GMR/BeatPicker#2]
Hi there,

I am currently using Beatpicker.js and have set some disabled dates. It works perfectly on desktop but when viewed on an IOS device (Iphone 5s)  the disabled dates aren't disabled. 

Do you know why might that be?

I noticed in the demo example ("multiple disable rules
NOTE THAT FIRST TO LAST RULE HAVE HIGH PRIORITY")
on this link - http://act1gmr.github.io/BeatPicker/demos.html does the same thing but the disable all dates works fine.

**Comment by cawo88** [comment]
I have two disable rules set by the way and have removed one to test and it doesn't work still.

**Comment by ACT1GMR** [comment]
thanx for reporting issue @cawo88 , but you should know that BeatPicker didnt issued any guarantee for working on mobile devices yet.but I will try your state ,if there is any problem will try a patch for it anyway thanx

**Comment by cawo88** [comment]
okay cool thanks.
