### ISSUE TITLE
How to get data from date ranges?

### ISSUE THREAD

**Issue by ghost** [ACT1GMR/BeatPicker#3]
How to get data from date ranges using POST method?
I mean how to get both of dates. Using BeatPicker you need put only one input field and the second one is create automatically.

I like to recieve 2 datas like from 2 inputs.

for example:
$_POST['from'] and $_POST['to']

**Comment by ACT1GMR** [comment]
Hi ,thanx for using BeatPicker
check this link:
http://act1gmr.github.io/BeatPicker/docs.html#methods/getSelectedEndDate

**Comment by ghost** [comment]
Aaaa ok. Now understand. Must use JS for send POST :+1:
