### ISSUE TITLE
Hitting clear reloads the page

### ISSUE THREAD

**Issue by dspstudio** [ACT1GMR/BeatPicker#5]
i integrated the date picker but the clear date button reloads my page and in the demo the page isn't reloaded

**Comment by ACT1GMR** [comment]
Thanx to using **BeatPicker** and wow that's weird please post your scenario and browser information

**Comment by dspstudio** [comment]
i have a form which is submitted when i hit the clear button.
you can access the form at http://fohe-bprc.forhe.ro/formular

**Comment by ACT1GMR** [comment]
OK I got it.this is because of type of button by default any button in form will behave as submit button if you dont specify the type of button.If you want override this behavior temporarily please do something like this till I release some patch for it.thanx for inform me about this defect.

``` javascript
myPicker.getPickerNodes().attr("type","button")
```
