### ISSUE TITLE
I can't select a specific date through code Whenever needed

### ISSUE THREAD

**Issue by vanabharathiraja** [ACT1GMR/BeatPicker#6]
Hi,

I required to select a specific date through javascript code. so, it should be highlighted/selected on beatpicker box. 

I believe this functionality  has not yet added in plugin. If you have any idea to achieve this, please share me, so I can implement in my app. Also please add this functionality in next version.

Regards,

**Comment by ACT1GMR** [comment]
Hi @vanabharathiraja this need force me to make it work for such a requirement you can check out this document to get what you need please download v01.2 from home page:
_doc_ : http://act1gmr.github.io/BeatPicker/docs.html#methods/selectDate
_download_ : http://act1gmr.github.io/BeatPicker/

**Comment by vanabharathiraja** [comment]
Thank you for the quick response and help.  Now, I can select specific date from code.

Thanks,
Bharathi
