### ISSUE TITLE
Beatpicker not closing when touch outside in touch devices(apple)

### ISSUE THREAD

**Issue by vanabharathiraja** [ACT1GMR/BeatPicker#9]
Hi,

The beatpicker date popup not closing when touch outside in apple devices(iphone, Ipad).

Note: it is fine in android touch devices.

Do I need to add specific event for this?

Regards,

**Comment by ACT1GMR** [comment]
Hi @vanabharathiraja **BeatPicker**  did not developed for handheld platform like iPod iPhone or even android devices its just something that may work or not I just didnt gave any guarantee for such support.But on v1.0.0 you can get special support for mobile devices as i mentioned in this topic #4 
but if its critical for you : define an id for your picker and close it manually check this example:
http://act1gmr.github.io/BeatPicker/demos.html#global-reference
